//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenge2.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourEventsOnly
    {
        public int eventDay { get; set; }
        public string eventMonth { get; set; }
        public int eventYear { get; set; }
        public decimal fee { get; set; }
        public int tourID { get; set; }
        public int eventID { get; set; }
    }
}
